// src/lib/countries.ts
export interface Country {
    code: string;
    name: string;
}

export const countries: Country[] = [
    { code: 'CN', name: '中国' },
    { code: 'US', name: '美国' },
    { code: 'JP', name: '日本' },
    { code: 'KR', name: '韩国' },
    { code: 'GB', name: '英国' },
    { code: 'FR', name: '法国' },
    { code: 'DE', name: '德国' },
    { code: 'RU', name: '俄罗斯' },
    { code: 'IN', name: '印度' },
    { code: 'BR', name: '巴西' },
    { code: 'CA', name: '加拿大' },
    { code: 'AU', name: '澳大利亚' },
    { code: 'SG', name: '新加坡' },
    { code: 'MY', name: '马来西亚' },
    { code: 'TH', name: '泰国' },
    { code: 'VN', name: '越南' },
    { code: 'ID', name: '印度尼西亚' },
    { code: 'PH', name: '菲律宾' },
    { code: 'TR', name: '土耳其' },
    { code: 'SA', name: '沙特阿拉伯' },
    // 新增国家
    { code: 'AM', name: '亚美尼亚' },
    { code: 'BD', name: '孟加拉国' },
    { code: 'CR', name: '哥斯达黎加' },
    { code: 'DK', name: '丹麦' },
    { code: 'EC', name: '厄瓜多尔' },
    { code: 'EG', name: '埃及' },
    { code: 'GI', name: '直布罗陀' },
    { code: 'GT', name: '危地马拉' },
    { code: 'GG', name: '根西岛' },
    { code: 'IE', name: '爱尔兰' },
    { code: 'JO', name: '约旦' },
    { code: 'KZ', name: '哈萨克斯坦' },
    { code: 'LA', name: '老挝' },
    { code: 'LT', name: '立陶宛' },
    { code: 'MO', name: '澳门' },
    { code: 'MD', name: '摩尔多瓦' },
    { code: 'NG', name: '尼日利亚' },
    { code: 'NO', name: '挪威' },
    { code: 'PS', name: '巴勒斯坦' },
    { code: 'QA', name: '卡塔尔' },
    { code: 'SI', name: '斯洛文尼亚' },
    { code: 'TT', name: '特立尼达和多巴哥' },
    { code: 'UY', name: '乌拉圭' },
    { code: 'AF', name: '阿富汗' },
    { code: 'AZ', name: '阿塞拜疆' },
    { code: 'BY', name: '白俄罗斯' },
    { code: 'IL', name: '以色列' },
    { code: 'PT', name: '葡萄牙' },
    { code: 'AE', name: '阿联酋' },
    { code: 'LV', name: '拉脱维亚' },
    { code: 'SK', name: '斯洛伐克' },
    { code: 'HU', name: '匈牙利' },
    { code: 'PE', name: '秘鲁' },
    { code: 'AT', name: '奥地利' },
    { code: 'BG', name: '保加利亚' },
    { code: 'NZ', name: '新西兰' },
    { code: 'CH', name: '瑞士' },
    { code: 'BE', name: '比利时' },
    { code: 'CO', name: '哥伦比亚' },
    { code: 'RO', name: '罗马尼亚' },
    { code: 'SE', name: '瑞典' },
    { code: 'IT', name: '意大利' },
    { code: 'CL', name: '智利' },
    { code: 'UA', name: '乌克兰' },
    { code: 'CZ', name: '捷克共和国' },
    { code: 'MX', name: '墨西哥' },
    { code: 'TW', name: '台湾' },
    { code: 'AR', name: '阿根廷' },
    { code: 'PL', name: '波兰' },
    { code: 'IR', name: '伊朗' },
    { code: 'NL', name: '荷兰' },
    { code: 'HK', name: '香港' },
    { code: 'ES', name: '西班牙' },
    { code: 'FI', name: '芬兰' },
];

export const getCountryName = (code: string): string => {
    const country = countries.find(c => c.code === code);
    return country ? country.name : '';
};
