services:
  app:
    image: mohistmc-frontend-${ENV}:${VERSION}
    build:
      context: ../..
      dockerfile: Dockerfile.app
    container_name: mohistmc_frontend_${ENV}
    restart: always
    ports:
      - "${APP_EXTERNAL_PORT}:3000"