name: Build and Deploy

on:
  push:
    tags:
      - '*'
    branches-ignore:
      - '**'

jobs:
  build-and-deploy:
    uses: MohistMC/devops/.github/workflows/build-and-deploy.yml@main
    with:
      tag: ${{ github.ref_name }}
    secrets: inherit