name: GitHub CI/CD

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build:
    if: github.ref_type == 'branch'
    uses: MohistMC/devops/.github/workflows/build.yml@1.0.20

  deploy:
    if: github.ref_type == 'tag'
    uses: MohistMC/devops/.github/workflows/deploy.yml@1.0.20
    with:
      tag: ${{ github.ref_name }}
    secrets: inherit
